version: '3'
volumes:
  mongo-data:
services:
  mongo:
    container_name: 'tezos-signature-mongo'
    image: 'mongo:4.2.3'
    ports:
      - '27017:27017'
    volumes:
      - 'mongo-data:/data/db'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: tezos-signature
    restart: unless-stopped
  mongo-express:
    container_name: 'tezos-signature-mongo-express'
    image: 'mongo-express:0.54.0'
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    restart: unless-stopped
    depends_on:
      - mongo
  mail:
    container_name: tezos-signature-mail
    image: gessnerfl/fake-smtp-server:1.3.0
    ports:
      - "5025:5025"
      - "5080:5080"
      - "5081:5081"
    environment:
      FAKESMTP_AUTHENTICATION_USERNAME: username
      FAKESMTP_AUTHENTICATION_PASSWORD: password
    restart: unless-stopped
  rest:
    container_name: tezos-signature-rest
    image: sword/signature-rest:local
    build: frontend/rest
    ports:
      - "9090:8080"
    volumes:
      - "./compose-config/carthagenet/application-rest.yml:/app/application.yml:ro"
    restart: unless-stopped
    depends_on:
      - mongo
      - daemon
  daemon:
    container_name: tezos-signature-daemon
    image: sword/signature-daemon:local
    build: backend/daemon
    volumes:
      - "./compose-config/carthagenet/application-daemon.yml:/app/application.yml:ro"
    restart: unless-stopped
    depends_on:
      - mongo
      - mail
