version: '3'
volumes:
  mongo-data:
services:
  mongo:
    image: 'mongo:4.2.3'
    container_name: 'tezos-signature-mongodb'
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: tezos-signature
    volumes:
      - 'mongo-data:/data/db'
  mongo-express:
    image: 'mongo-express:0.54.0'
    container_name: 'tezos-signature-mongodb-express'
    restart: unless-stopped
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
  mail:
    container_name: tezos-signature-mail
    image: gessnerfl/fake-smtp-server:1.3.0
    restart: unless-stopped
    ports:
      - "5025:5025"
      - "5080:5080"
      - "5081:5081"
    environment:
      FAKESMTP_AUTHENTICATION_USERNAME: username
      FAKESMTP_AUTHENTICATION_PASSWORD: password
#  web:
#    container_name: tezos-signature-web
#    image: sword/signature-web
#    build: web
#    ports:
#      - "8080:8080"