version: '3'
services:
  mongo:
    image: 'mongo:4.2.3'
    container_name: 'tezos-signature-mongodb'
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
  mongo-express:
    image: 'mongo-express:0.54.0'
    container_name: 'tezos-signature-mongodb-express'
    restart: unless-stopped
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password


