sign:
  tree:
   maximunLeaf: 1024
management:
  endpoints:
    web:
      exposure:
        include: info,health
    health:
      show-details: always
spring:
  data:
    mongodb:
      auto-index-creation: false
      uri: mongodb://root:password@mongodb:27017/tezos-signature?authSource=admin
logging:
  level:
    root: info
    com:
      sword: debug
    web: warn
    org:
      springframework:
        security: info
jwt:
  secret: ffe50f21d8359de7245dc13777812c2a
  issuer: "Tezos@Signature"
  duration : 2h
tezos:
  indexer:
    url: "https://api.carthagenet.tzstats.com"
  validation:
    minDepth: 30