sign:
  tree:
    maximumLeaf: 1024 # Maximum leaves number per merkle tree.
management:
  endpoints:
    web:
      exposure:
        include: info,health
    health:
      show-details: always
spring:
  data:
    mongodb:
      auto-index-creation: false
      uri: mongodb://root:password@mongo:27017/tezos-signature?authSource=admin
  resources:
    static-locations: "classpath:/public-web-resources/"
logging:
  level:
    root: info
    com:
      sword: debug
    web: warn
    org:
      springframework:
        security: info
jwt:
  secret: ffe50f21d8359de7245dc13777812c2a # Secret for authentication tokens generation/parsing.
  issuer: "Tezos@Signature"
  duration: 2h # Expiration duration of client session tokens.
tezos:
  contract:
    address: "KT1Acfs1M5FXHGYQpvdKUwGbZtrUkqrisweJ" # Mainnet smart contract address
  indexer:
    url: "https://api.tzstats.com"
  validation:
    minDepth: 30
    minAge: 2h
  chain: "TEZOS_MAINNET"
  urls:
    api:
      storage: "https://api.tzstats.com/explorer/bigmap/$bigmapId/$rootHash"
      transaction: "https://api.tzstats.com/explorer/op/$transactionHash"
    web:
      provider: "http://localhost:9090" # To replace by the public URL of the REST container.
