sign:
  tree:
   maximumLeaf: 3
spring:
  main:
    web-application-type: none
  data:
    mongodb:
      auto-index-creation: false
      uri: mongodb://root:password@localhost:27017/tezos-signature?authSource=admin
  batch:
    initialize-schema: always
    datasource:
      initialize: true
      driver-class-name: org.hsqldb.jdbcDriver
      jdbcUrl: jdbc:hsqldb:mem:jobDataSource;sql.enforce_strict_size=true;hsqldb.tx=mvcc
      username: sa
      password:
  mail:
    host: localhost
    port: 5025
    username: username
    password: password
    sender: signer@signature.com
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writeTimeout: 5000
          starttls:
            enable: true
        debug: true
logging:
  level:
    root: info
    com:
      sword: debug
    web: warn
    org:
      springframework:
        security: info
        data: info
      ej4tezos: info
daemon:
  anchoring:
    delay: 1m
  callback:
    maxTry : 5
    delay : 2m
  validation:
    delay: 1m
    timeout: 10m
  poller:
    fixedRate: 10000
jasypt:
  encryptor:
    password: secret
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
jwt:
  secret: ffe50f21d8359de7245dc13777812c2a
  issuer: "Tezos@Signature"
tezos:
  keys:
    admin:
      hash: "tz1VSUr8wwNhLAzempoch5d6hLRiTh8Cjcjb"
      publicKey: "edpkvGfYw3LyB1UcCahKQk4rF2tvbMUk8GFiTuMjL75uGXrpvKXhjn"
      secretKey: ENC(Sjy2KdrcmMKKyo294ZaFmpuw2gIEj7jArV/0PM530EOGm4MGXrIP6OWY4It6HTpKks0GinKiA+vWJdAZRpbSyA==)
    frodon:
      hash: "tz1aSkwEot3L2kmUvcoxzjMomb9mvBNuzFK6"
      publicKey: "edpkurPsQ8eUApnLUJ9ZPDvu98E8VNj4KtJa1aZr16Cr5ow5VHKnz4"
      secretKey: ENC(LvGfsJLxfwNoOIrKgdp9Y4E9EXyJZGe+bBhacjAuxDUIJZBj54O09suxCx6Y/Nzdq4+p8xbs0fdyXyPT+HY1vQ==)
  contract:
    address: KT1XR5tZHWxMU36eTq3qFn3fvnmDvCTc8NTD
  node:
    url: "http://127.0.0.1:18731"
  indexer:
    url: "http://127.0.0.1:8001"
  validation:
    minDepth: 30
