sign:
  tree:
   maximunLeaf: 3

spring:
  main:
    web-application-type: none
  data:
    mongodb:
      auto-index-creation: false
      uri: mongodb://root:password@localhost:27017/tezos-signature?authSource=admin
  batch:
    initialize-schema: always
    datasource:
      initialize: true
      driver-class-name: org.hsqldb.jdbcDriver
      jdbcUrl: jdbc:hsqldb:mem:jobDataSource;sql.enforce_strict_size=true;hsqldb.tx=mvcc
      username: sa
      password:
  mail:
    host: localhost
    port: 5025
    username: username
    password: password
    sender: signer@signature.com
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writeTimeout: 5000
          starttls:
            enable: true
        debug: true
logging:
  level:
    root: info
    com:
      sword: debug
    web: warn
    org:
      springframework:
        security: info
        data: info
      ej4tezos: info
daemon:
  anchoring:
    delay: 1m
  callback:
    maxTry : 5
    delay : 2m
  validation:
    delay: 1m
    timeout: 10m
  poller:
    fixedRate: 10000
jasypt:
  encryptor:
    password: secret
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
jwt:
  secret: ffe50f21d8359de7245dc13777812c2a
  issuer: "Tezos@Signature"
tezos:
  keys:
    admin:
      address: tz1VSUr8wwNhLAzempoch5d6hLRiTh8Cjcjb
      publicKey: "edpkvGfYw3LyB1UcCahKQk4rF2tvbMUk8GFiTuMjL75uGXrpvKXhjn"
      secretKey: ENC(7IpOdQ6/9gwjZPE3HF1ab8uGlk4KoELm0NChxzUaGL2A7BFXMoL41P5j7f76L4Ap/CoiDk/6I6gtXwQFOY5JRg==)
  contract:
    address: KT1XMzkvjfiwLFYbHN5uGymNffL8vquTnAzq
  node:
    url: "http://127.0.0.1:18731"
  indexer:
    url: "http://127.0.0.1:8000"
  validation:
    minDepth: 30
