---
- name: Add user to docker group.
  user:
    name: "{{ USER }}"
    groups: docker
    append: true
  become: true

- name: Install Pip.
  apt:
    name: python3-pip
    state: present
  become: true

- name: Install Docker Python library.
  pip:
    name: docker
    state: present
  become: true

- name: Install Docker Compose Python library.
  pip:
    name: docker-compose
    state: present
  become: true