---
- hosts: all
  vars_files: vars.yml
  vars:
    USER: "{{ ansible_ssh_user }}"
    USERDIR: "/home/{{ USER }}"
    ansible_python_interpreter: /usr/bin/python3
  pre_tasks:
    - name: Update apt cache if needed and install some packages.
      apt:
        update_cache: yes
        cache_valid_time: 3600
        name: "{{ item }}"
        state: present
      with_items:
        - vim
      become: true
  roles:
    - role: geerlingguy.docker
      become: true
  tasks:
    - import_tasks: tasks/docker.yml