server:
  port: 9090
sign:
  tree:
    maximumLeaf: 3
management:
  endpoints:
    web:
      exposure:
        include: info,health
    health:
      show-details: always
spring:
  data:
    mongodb:
      auto-index-creation: false
      uri: mongodb://root:password@localhost:27017/tezos-signature?authSource=admin
  resources:
    static-locations: "classpath:/public-web-resources/"
logging:
  level:
    root: info
    com:
      sword: debug
    web: warn
    org:
      springframework:
        security: info
        data: info
jwt:
  secret: ffe50f21d8359de7245dc13777812c2a
  issuer: "Tezos@Signature"
  duration: 2h
tezos:
  contract:
    address: "TEZOS_CONTRACT_ADDRESS" # To replace by the actual smart contract address.
  indexer:
    url: "http://127.0.0.1:8000"
  validation:
    minDepth: 30
    minAge: 2h
  chain: "TEZOS_CARTHAGENET_SANDBOX"
  urls:
    api:
      storage: "http://127.0.0.1:8000/explorer/bigmap/$bigmapId/$rootHash"
      transaction: "http://127.0.0.1:8000/explorer/op/$transactionHash"
    web:
      provider: "http://127.0.0.1:8082"

