sign:
  tree:
   maximumLeaf: 1024
management:
  endpoints:
    web:
      exposure:
        include: info,health
    health:
      show-details: always
spring:
  data:
    mongodb:
      auto-index-creation: false
      uri: mongodb://root:password@mongo:27017/tezos-signature?authSource=admin
  resources:
    static-locations: "classpath:/public-web-resources/"
logging:
  level:
    root: info
    com:
      sword: debug
    web: warn
    org:
      springframework:
        security: info
jwt:
  secret: ffe50f21d8359de7245dc13777812c2a
  issuer: "Tezos@Signature"
  duration : 2h
tezos:
  contract:
    address: "KT1MDJeDXHDeq1SojdCoiQKx7ZktrV12Zpk7"
  indexer:
    url: "http://tzindex:8000"
  validation:
    minDepth: 30
  chain: "TEZOS_CARTHAGENET"
  urls:
    api:
      storage: "http://tzindex:8000/explorer/bigmap/$bigmapId/$rootHash"
      transaction: "http://tzindex:8000/explorer/op/$transactionHash"
    web:
      provider: "http://rest:8080"
